name: Deploy Python Bot to Azure

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsque vous poussez sur la branche "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Choisissez votre version Python

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          cd TDIA2_bot
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Déployer sur Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Tdia2-Bot"  # Nom de votre App Service Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: TDIA2_bot  # Spécifiez le dossier contenant votre code
