name: bot CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/bot-appservice.yml"
permissions:
    contents: read
    id-token: write
jobs:
  build_and_deploy: 
    runs-on: ubuntu-latest
    environment:
      name: BotEnv
      url: ${{steps.deploy-to-webapp.outputs.webapp-url}}
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: Tdia2-bot
        package: ./TDIA2_bot
